spring:
  application:
    name: mcqprep
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USER}&password=${DB_PASS}&sslmode=require
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate    # Flyway owns schema changes, Hibernate just verifies
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org:
      flywaydb: DEBUG


# application.yml
gemini:
  api-key: ${API_KEY}
  model: ${AI_MODEL}
  base-url: ${AI_URL}

management:
  endpoint:
    health:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health

miniapp:
  local:
    url: ${MINI_APP_LOCAL_URL}
  prod:
    url: ocker{MINI_APP_PROD_URL}